# permissions for end users to view configmaphistories.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: configmaphistory-viewer-role
rules:
- apiGroups:
  - test.opskumu.com
  resources:
  - configmaphistories
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - test.opskumu.com
  resources:
  - configmaphistories/status
  verbs:
  - get
